-- A relational database consists of multiple related tables linking together using common columns, which are known as foreign key columns. Because of this, the data in each table is incomplete from the business perspective.
-- A join is a method of linking data between one (self-join) or more tables based on the values of the common column between the tables.
-- MySQL supports the following types of joins:
-- Inner join
-- Left join
-- Right join
-- Cross join
-- To join tables, you use the cross join, inner join, left join, or right join clause. The join clause is used in the SELECT statement appeared after the FROM clause.
-- INNER JOIN: Returns records that have matching values in both tables
-- LEFT JOIN: Returns all records from the left table, and the matched records from the right table
-- RIGHT JOIN: Returns all records from the right table, and the matched records from the left table
-- CROSS JOIN: Returns all records from both tables
-- BASIC SYNTAX
-- SELECT
--     column_list
-- FROM
--     table_1
--     LEFT JOIN table_2 ON join_condition;

-- SELECT
--     column_list
-- FROM
--     table_1
--     INNER JOIN table_2 ON join_condition;