-- The MySQL OR operator is a logical operator that combines two Boolean expressions.
SELECT 1 OR 1, 1 OR 0, 0 OR 1;
-- +--------+--------+--------+
-- | 1 OR 1 | 1 OR 0 | 0 OR 1 |
-- +--------+--------+--------+
-- |      1 |      1 |      1 |
-- +--------+--------+--------+
-- 1 row in set (0.00 sec)
mysql> SELECT
    -> customername,
    -> country,
    -> creditLimit
    -> FROM
    -> customers
    -> WHERE(country = 'USA'
    -> OR country = 'France')
    ->   AND creditlimit > 100000;
-- +------------------------------+---------+-------------+
-- | customername                 | country | creditLimit |
-- +------------------------------+---------+-------------+
-- | La Rochelle Gifts            | France  |   118200.00 |
-- | Mini Gifts Distributors Ltd. | USA     |   210500.00 |
-- | Land of Toys Inc.            | USA     |   114900.00 |
-- | Saveley & Henriot, Co.       | France  |   123900.00 |
-- | Muscle Machine Inc           | USA     |   138500.00 |
-- | Diecast Classics Inc.        | USA     |   100600.00 |
-- | Collectable Mini Designs Co. | USA     |   105000.00 |
-- | Marta's Replicas Co.         | USA     |   123700.00 |
-- | Mini Classics                | USA     |   102700.00 |
-- | Corporate Gift Ideas Co.     | USA     |   105000.00 |
-- | Online Diecast Creations Co. | USA     |   114200.00 |
-- +------------------------------+---------+-------------+
-- 11 rows in set (0.00 sec)

